version: "3.3"

networks:
  internal:
    driver: bridge


services:
  studentsdb:
    image: mongo:latest
    restart: always
    networks:
      - internal
    ports:
      - "27017:27017"

  student-service:
    build: .
    networks:
      - internal
    ports:
      - "8000:8000"