version: "3.3"

networks:
  internal:
    driver: bridge


services:
  studentsdb:
    image: mongo:latest
    networks:
      - internal
    restart: always
    environment:
      MONGO_INITDB_DATABASE: studentsdb
    ports:
      - "27017:27017"
    
  redis:
    image: redis:latest
    networks:
      - internal
    restart: always
    ports:
      - "6380:6379"

  app:
    build: .
    networks:
      - internal
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - studentsdb
    environment:
    - MONGODB_URI= "mongodb://studentsdb:27017"
    - REDIS_HOST= redis
    - REDIS_PORT= 6379
    expose:
      - "8000"
